# Custom Language File for Launcher Customizer

[ejs.app]
title = "NeoLauncher indev"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/NeoCubeS4/NeoLauncher"
supportLink = "https://github.com/NeoCubeS4/NeoLauncher/issues"

[ejs.welcome]
welcomeHeader = "Hello"
welcomeDescription = "lorem imp."
welcomeDescCTA = "Lotem imp."
