# Custom Language File for Launcher Customizer

[ejs.app]
title = "NeoLauncher indev"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/NeoCubeS4/NeoLauncher"
supportLink = "https://github.com/NeoCubeS4/NeoLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur NeoLauncher !"
welcomeDescription = "Vous êtes à quelques pas de rejoindre NeoCube ! Pour cela, vous devrez vous connecter à votre compte Microsoft (avec Minecraft Premium)."
welcomeDescCTA = "Si vous rencontrez des difficultés ou si vous avez des remarques à faire, n'hésitez pas à nous les signaler sur notre Discord ou dans l'onglet "Issues" de notre GitHub."
